### PR TITLE
Add float for intervals + Add NetSpeed Compact and TotalNetSpeed

### PR DESCRIPTION
**Pull request by prateekmedia**
This PR is for adding that functionality of floats in intervals, also it will not impact performance cause anyone cannot enter value less than 1 sec(< 1 sec was causing the real performance issue).

Second thing I added was Compact net Speed which basically is UP+DOWN and Total net speed with sigma in front of it which basically is TOTAL UP+TOTAL DOWN, which will help users to track their download and upload speed more effectively. Below is the preview in ubuntu budgie   
image

IMO MiB and GiB looks ugly so if you can simply rename them to MB or GB that can be good but again its personal opinion , I have included this in this PR. I have also changed conversion rate from 1MiB=1024 KiB to 1MB = 1024KB

### CODE REVIEW

**Comment by fossfreedom** [comment]
The PR looks ok from a quick read.

However remember KiB is not the same as KB ... different number if bytes.

Think probably a separate option is needed to change the calculation of KiB vs KB for example - that's a different issue.

So if you can back out those changes please I can merge.

**Comment by prateekmedia** [comment]
> The PR looks ok from a quick read.
> 
> However remember KiB is not the same as KB ... different number of bytes.
> 
> Think probably a separate option is needed to change the calculation of KiB vs KB for example - that's a different issue.
> 
> So if you can back out those changes please I can merge.

Sure Maybe in one or two days, I will get back to you when I'm done. 👍

**Comment by prateekmedia** [comment]
> So if you can back out those changes please I can merge.

DONE :), I tried my best to make a method or function of common code but I couldn't, else everything is perfect   I think.

PS : used 1KB = 1000B

**Comment by prateekmedia** [comment]
> So if you can back out those changes please I can merge.

Are you there?

**Comment by prateekmedia** [comment]
> 
> So if you can back out those changes please I can merge.

Are You their? @fossfreedom

**Comment by fossfreedom** [comment]
LGTM - thanks!

**Pull request merged**
