### PR TITLE
Edit to work for mate-system-monitor

### PR DESCRIPTION
**Pull request by aandmsantos0910**

### CODE REVIEW

**Comment by aandmsantos0910** [comment]
This is the change I made to get mate-system-monitor to launch from the applet.

**Comment by fossfreedom** [comment]
Cheers for this.

There is a big but. The applet is used by more than just mate system monitor users. So the change you have suggested will break gnome system monitor users.

**Comment by aandmsantos0910** [comment]
Ah, sorry was not aware. Will keep that in mind. Thank you for the heads up. :-)

**Comment by fossfreedom** [comment]
fixed in this commit https://github.com/fossfreedom/indicator-sysmonitor/commit/53c9852b743b0d48bfc16b992a41fbfb39a95091

**Pull request closed without merging**
